// Code generated by "stringer -type adjustFlag -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoAdjusted-1]
	_ = x[BackwordAdjusted-2]
	_ = x[ForwardAdjusted-3]
}

const _adjustFlag_name = "不复权后复权前复权"

var _adjustFlag_index = [...]uint8{0, 9, 18, 27}

func (i adjustFlag) String() string {
	i -= 1
	if i >= adjustFlag(len(_adjustFlag_index)-1) {
		return "adjustFlag(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _adjustFlag_name[_adjustFlag_index[i]:_adjustFlag_index[i+1]]
}
