// Code generated by "stringer -type bondType -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BondClean-1]
	_ = x[BondDirty-2]
	_ = x[BondROI-3]
}

const _bondType_name = "净价全价收益率"

var _bondType_index = [...]uint8{0, 6, 12, 21}

func (i bondType) String() string {
	i -= 1
	if i >= bondType(len(_bondType_index)-1) {
		return "bondType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _bondType_name[_bondType_index[i]:_bondType_index[i+1]]
}
