// Code generated by "stringer -type cfnMode -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CfnStartToEnd-1]
	_ = x[CfgEndCound-2]
}

const _cfnMode_name = "开始到结束中间的所有资讯到结束时间的近count条资讯"

var _cfnMode_index = [...]uint8{0, 36, 71}

func (i cfnMode) String() string {
	i -= 1
	if i >= cfnMode(len(_cfnMode_index)-1) {
		return "cfnMode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _cfnMode_name[_cfnMode_index[i]:_cfnMode_index[i+1]]
}
