// Code generated by "stringer -type CompanyType -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompanyInvalid-0]
	_ = x[CompanyGeneral-1]
	_ = x[CompanyInsurance-2]
	_ = x[CompanyBank-3]
	_ = x[CompanySecurity-4]
}

const _CompanyType_name = "未知公司类型一般企业保险公司商业银行证券公司"

var _CompanyType_index = [...]uint8{0, 18, 30, 42, 54, 66}

func (i CompanyType) String() string {
	if i >= CompanyType(len(_CompanyType_index)-1) {
		return "CompanyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompanyType_name[_CompanyType_index[i]:_CompanyType_index[i+1]]
}
