// Code generated by "stringer -type currency -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CurrOrigin-1]
	_ = x[CurrCNY-2]
	_ = x[CurrUSD-3]
	_ = x[CurrHKD-4]
}

const _currency_name = "原始币种人民币美元港元"

var _currency_index = [...]uint8{0, 12, 21, 27, 33}

func (i currency) String() string {
	i -= 1
	if i >= currency(len(_currency_index)-1) {
		return "currency(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _currency_name[_currency_index[i]:_currency_index[i+1]]
}
