// Code generated by "stringer -type eqMsgType -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgTypeErr-0]
	_ = x[MsgTypeRsp-1]
	_ = x[MsgTypePartialRsp-2]
	_ = x[MsgTypeOther-3]
}

const _eqMsgType_name = "错误消息应答部分应答其他"

var _eqMsgType_index = [...]uint8{0, 12, 18, 30, 36}

func (i eqMsgType) String() string {
	if i >= eqMsgType(len(_eqMsgType_index)-1) {
		return "eqMsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _eqMsgType_name[_eqMsgType_index[i]:_eqMsgType_index[i+1]]
}
