// Code generated by "stringer -type eqValueType -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueNull-0]
	_ = x[ValueChar-1]
	_ = x[ValueBool-2]
	_ = x[ValueShort-3]
	_ = x[ValueUShort-4]
	_ = x[ValueInt-5]
	_ = x[ValueUInt-6]
	_ = x[ValueInt64-7]
	_ = x[ValueUInt64-8]
	_ = x[ValueSingle-9]
	_ = x[ValueDouble-10]
	_ = x[ValueBytes-11]
	_ = x[ValueString-12]
}

const _eqValueType_name = "NullCharBoolShortUshortIntUintInt64Uint64SingleDoubleBytesString"

var _eqValueType_index = [...]uint8{0, 4, 8, 12, 17, 23, 26, 30, 35, 41, 47, 53, 58, 64}

func (i eqValueType) String() string {
	if i >= eqValueType(len(_eqValueType_index)-1) {
		return "eqValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _eqValueType_name[_eqValueType_index[i]:_eqValueType_index[i+1]]
}
