// Code generated by "stringer -type funcType -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FuncCSD-0]
	_ = x[FuncCSS-1]
	_ = x[FuncCSES-2]
}

const _funcType_name = "CSDCSSCSEC"

var _funcType_index = [...]uint8{0, 3, 6, 10}

func (i funcType) String() string {
	if i >= funcType(len(_funcType_index)-1) {
		return "funcType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _funcType_name[_funcType_index[i]:_funcType_index[i+1]]
}
