// Code generated by "stringer -type isp -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ISP_CT-1]
	_ = x[ISP_CM-2]
	_ = x[ISP_CU-3]
}

const _isp_name = "电信移动联通"

var _isp_index = [...]uint8{0, 6, 12, 18}

func (i isp) String() string {
	i -= 1
	if i >= isp(len(_isp_index)-1) {
		return "isp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _isp_name[_isp_index[i]:_isp_index[i+1]]
}
