// Code generated by "stringer -type period -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Daily-1]
	_ = x[Weekly-2]
	_ = x[Monthly-3]
	_ = x[Yearly-4]
}

const _period_name = "日频周频月频年频"

var _period_index = [...]uint8{0, 6, 12, 18, 24}

func (i period) String() string {
	i -= 1
	if i >= period(len(_period_index)-1) {
		return "period(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _period_name[_period_index[i]:_period_index[i+1]]
}
