// Code generated by "stringer -type ReportName -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RptNameInvalid-0]
	_ = x[RptNameBalance-1]
	_ = x[RptNameIncome-2]
	_ = x[RptNameCashFlow-3]
	_ = x[RptNamePrediction-4]
}

const _ReportName_name = "未知报表名资产负债表利润表现金流表盈利预测"

var _ReportName_index = [...]uint8{0, 15, 30, 39, 51, 63}

func (i ReportName) String() string {
	if i >= ReportName(len(_ReportName_index)-1) {
		return "ReportName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReportName_name[_ReportName_index[i]:_ReportName_index[i+1]]
}
