// Code generated by "stringer -type ReportType -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RptTypeInvalid-0]
	_ = x[RptTypeCombined-1]
	_ = x[RptTypeCombAdjust-2]
	_ = x[RptTypeParent-3]
	_ = x[RptTypeParentAdjust-4]
}

const _ReportType_name = "未知报表类型合并报表合并报表调整母公司报表母公司报表调整"

var _ReportType_index = [...]uint8{0, 18, 30, 48, 63, 84}

func (i ReportType) String() string {
	if i >= ReportType(len(_ReportType_index)-1) {
		return "ReportType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReportType_name[_ReportType_index[i]:_ReportType_index[i+1]]
}
