// Code generated by "stringer -type reportName -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RptNameInvalid-0]
	_ = x[RptNameBalance-1]
	_ = x[RptNameIncome-2]
	_ = x[RptNameCashFlow-3]
	_ = x[RptNamePrediction-4]
	_ = x[RptNameIdxConstituent-5]
}

const _reportName_name = "未知报表名资产负债表利润表现金流表盈利预测指数成分表"

var _reportName_index = [...]uint8{0, 15, 30, 39, 51, 63, 78}

func (i reportName) String() string {
	if i >= reportName(len(_reportName_index)-1) {
		return "reportName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _reportName_name[_reportName_index[i]:_reportName_index[i+1]]
}
