// Code generated by "stringer -type RptSourceType -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RptSrcInvalid-0]
	_ = x[RptSrcSeason1-1]
	_ = x[RptSrcSeason2-2]
	_ = x[RptSrcSeason3-3]
	_ = x[RptSrcSeason4-4]
}

const _RptSourceType_name = "未知报告来源一季报半年报三季报年报"

var _RptSourceType_index = [...]uint8{0, 18, 27, 36, 45, 51}

func (i RptSourceType) String() string {
	if i >= RptSourceType(len(_RptSourceType_index)-1) {
		return "RptSourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RptSourceType_name[_RptSourceType_index[i]:_RptSourceType_index[i+1]]
}
