// Code generated by "stringer -type sortOrder -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DateASC-1]
	_ = x[DateDESC-2]
}

const _sortOrder_name = "DateASCDateDESC"

var _sortOrder_index = [...]uint8{0, 7, 15}

func (i sortOrder) String() string {
	i -= 1
	if i >= sortOrder(len(_sortOrder_index)-1) {
		return "sortOrder(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _sortOrder_name[_sortOrder_index[i]:_sortOrder_index[i+1]]
}
