// Code generated by "stringer -type ttmType -linecomment"; DO NOT EDIT.

package choice4go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TTMRptEndDate-1]
	_ = x[TTMRptAnounceDate-2]
}

const _ttmType_name = "报表截止期报表公告期"

var _ttmType_index = [...]uint8{0, 15, 30}

func (i ttmType) String() string {
	i -= 1
	if i >= ttmType(len(_ttmType_index)-1) {
		return "ttmType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ttmType_name[_ttmType_index[i]:_ttmType_index[i+1]]
}
